# -*- coding: utf-8 -*-
"""batch32_DS_GenAi_AgenticAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dz6lTwTsTKuSS04esfWqPPodCUk0We8j
"""

print("welcome to the python programing")

print("""welcome to the python programming""")

print('''welcome to the python programming''')

help(print)

import keyword
keyword.kwlist

print(keyword.iskeyword("for"))
print(keyword.iskeyword("float"))
print(keyword.iskeyword("char"))
print(keyword.iskeyword("double"))

print(keyword.iskeyword("if"))
print(keyword.iskeyword("for"))
print(keyword.iskeyword("else"))
print(keyword.iskeyword("try"))
print(keyword.iskeyword("catch"))

x = keyword.kwlist
print("The total number of keywords are",len(x))

help(input)

fname=input("enter your first name=")
lname=input("enter your last name=")
print("your full name is",fname,lname)
print("your full name is ",lname,fname)

!cat /proc/cpuinfo





import platform
  print(platform.platform())
  print(platform.python_version())
  print(platform.version())
  print(platform.uname())
  print(platform.machine())
  print(platform.architecture)
  print(platform.processor())





#List_of_Lists
A=[2]*3
print(A)
B=[[2]*3]*2
print(B)
C=[[1,0]*1]*5
print(C)











import os
print(os.getcwd())
print(os.listdir())
print(os.name))
print(os.getenv('PATH'))
#print(os.getlogin())
print(os.getpid))
print(os.getpid))

# 1 python variables must begin with a letter(a -z ,A - Z) or underscore(_)
 abc=123
xyz="Hello"
Abc=321
_a=190
a_=123
print(abc)
print(xyz)
print(Abc)
print(_a)
print(a_)
#1abc=100

#2 python variables should be characters like letters ,numbers  or _
abc123=10
print(abc123)
ABC1234=100
print(ABC1234)
_abc123=10
print(_abc123)
_ABC123456=100
print(_ABC123456)
print(abc123,ABC1234,_abc123,_ABC123456)

a=1
b=2
a=4
b=10
print(a+b)
print(abc123,ABC1234,_abc123,_ABC123456)

print(print(a+b))

#3 python variables are case sensitive
uname="bharath sir"
password="hello123@@"
print(uname)
print(password)

#4 python variables can be any resonable length
siti_admin_login="uname"
siti_admin_password="hello123@@"

#5 python variables must not be reserved word or keyword
if=10
for="Hello"

#6 The variable names should be written in camelcase or pascal-case or snake_case
#pascal-case paypal,Fedx
pystr="PYTHON"
print(pystr)
pyInt=12345
print(pyInt)
pyfloat=1.99
print(pyfloat)
#camelcase ios,iphone,eBAY
pyStr="PYTHON"
print(pyStr)
pyInt=199
pyFloat=1.99
print(pyFloat)
#snake_case
py_str="PYTHON"
print(py_str)
py_int=199
print(py_int)
py_float=1.99
print(py_float)

#python supports the following literals:
# I.string literals:
PYSTR="PYTHON"
print(PYSTR)
# II.Numeric literals: 1 int 2 long 3 float 4 complex
PYINT=199
print(PYINT)
PYFLOAT=1.99
print(PYFLOAT)
PYCOMPLEX=1+2j
print(PYCOMPLEX)
#III. Boolean literals:True or False
PYBOOL=True
print(PYBOOL)
PYBOOL=False
print (PYBOOL)
# IV.special literals:None ==> In python is same as "null", means non existent ,not known
PYSPECIAL=None
print(PYSPECIAL)
# V.Literals collections:list,tuple, set & dict
PYLIST=[1,2,3,4,5]
print(PYLIST)
PYTUPLE=(1,2,3,4,5)
print(PYTUPLE)
PYSET={1,2,3,4,5}
print(PYSET)
PYDICT={1:"one",2:"two",3:"three",4:"four",5:"five"}
print(PYDICT)

PyList=["Big Data", "Hadoop", "Spark", "IoT"]
print(PyList[0])
print(PyList[0],PyList[3])
print(PyList[-1])
print(PyList[4])

a=89
b=99
a&b

a=111
b=222
a&b

a=10
b=20
a|b

a=10
b=20
a^b

a=100
b=200
a^b

for x in range (1,3):
  for y in range (1,3):
    print ('%d *% d =%d' %(x,y,x*y))

for x in range (2,5):
  for y  in range (2,5):
    print ('%d *% d =%d' %(x,y,x*y))

str = "Hello How are You"
print(str.replace("You", "U"))
print(str.replace("are", "R"))
str = "Hello How are are You"
print(str.replace("are", "R"))
print(str.replace("are", "R",1))

a=[1,2,3,4,5,6]
b=[2,3]
result=[x+y for x in a for y in b]
print(result)

pyDict={1:"Hadoop"}
print(pyDict)#{1:'Hadoop'}
pyDict[2]="spark"
print(pyDict)#{1:'Hadoop',2:'spark'}
pyDict[1]="H2O"
print(pyDict)

pycourse={1:"python",2:"ML",3:"DS"}
print(pycourse)
for item in pycourse:
  print(item)



#clear()
pyDict={1:"Hadoop",2:"Big Data"}
print(pyDict)
pyDict.clear()
print(pyDict)

#copy()
pyDict={1:"Hadoop",2:"Big Data",3:"python"}
pyDict1=pyDict.copy()
print(pyDict)
print(pyDict1)

person={"name": 'john',"age":36,"country":'Norway'}
print(person)

PyDict = {1: "Bigdata", 2: "Hadoop"}
print(type(PyDict))
print(PyDict)

PyCourses = {1: "PYTHON",2: "ML", 3: "DS" }
print(PyCourses)
for item in PyCourses.values():
    print(item)

PyList=[1,[2,[3,[4,[5]]]]]
print(PyList[0])
print(PyList[1][0])
print(PyList[1][1][0])

PyFruits=["Apple", "Banana", "Mango", "Grapes", "Orange"]
print(PyFruits[1:4])
print(PyFruits[ :3])
print(PyFruits[-4:])
print(PyFruits[-3:-1])

PyTuple = ("Data Science")
print(type(PyTuple)) #<class 'str'>
PyTuple = ("Data Science",)
print(type(PyTuple))#<class 'tuple'>
PyTuple = "Data Science",
print(type(PyTuple)) #<class 'tuple'>

MyTuple=('a',[1,2])
print(type(MyTuple))
print(MyTuple[0])
print(MyTuple[1])
print(MyTuple[1][1])
MyTuple[1][1]='4'
print(MyTuple)

MyTuple[1][1]='4'
print(MyTuple)